source 'https://github.com/CocoaPods/Specs.git'
# Target OS Version
platform :ios, '8.0'

# Inhibit warnings from dependencies
inhibit_all_warnings!
use_frameworks!

# Alamofire
pod 'Alamofire', '~> 3.2.1'
pod 'SwiftyJSON'

# Google Analytics
pod  'GoogleAnalytics'

# UI
pod 'SDWebImage', '~> 3.5'
pod 'SVProgressHUD', '~> 1.0'
pod 'UIView+AutoLayout', '~> 1.3'

# QR code library
pod 'ZBarSDK', '~> 1.3.1'

# Miscellaneous Utils
pod 'NSDate+TimeAgo', '~> 1.0.2'

# Push notifications
pod 'Localytics', '~> 3.8'
