source 'https://github.com/CocoaPods/Specs.git'
# Target OS Version
platform :ios, '8.0'

# Inhibit warnings from dependencies
inhibit_all_warnings!
use_frameworks!

abstract_target 'ScalaDaysPods' do
  # Alamofire
  pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :tag => '4.5.1'
  pod 'SwiftyJSON', '3.1.4'
  
  target 'ScalaDays' do
    # Google Analytics
    pod 'GoogleAnalytics'
          
    # UI
    pod 'SDWebImage', '~> 3.5'
    pod 'SVProgressHUD', '~> 1.0'
    pod 'UIView+AutoLayout', '~> 1.3'
    
    # QR code library
    pod 'ZBarSDK', '~> 1.3.1'
    
    # Miscellaneous Utils
    pod 'NSDate+TimeAgo', '~> 1.0.2'
    
    # Push notifications
    pod 'Localytics', '~> 5.1.0'
  end

  target 'ScalaDaysTests' do
  end
end
